module: Kitura-SMTP
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-SMTP/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-SMTP.xcodeproj, -target, Kitura-SMTP, LIBRARY_SEARCH_PATHS=.build/debug]